test_node:
  image: node:alpine
  script:
    - node --version
    - npm --version
    - npm install
    - npm test

test_ubuntu:
  image: ubuntu
  script:
    - apt-get update
    - apt-get install curl git -qq
    - curl -sL https://deb.nodesource.com/setup_8.x | bash -
    - apt-get install nodejs -qq
    - git clone https://github.com/DontPanic345/MarsRoverProblem.git
    - cd MarsRoverProblem
    - node --version
    - npm --version
    - npm install
    - npm test
    