# build:
#   image: node
#   script:
#     - node --version
#     - npm --version
#     - which node
#     - which npm
#     - npm install

test:
  image: node
  script:
    - node --version
    - npm --version
    - npm install
    - npm test

